
let data_Eng = [
    [    { 
            "name": "Mercury",
            "image":"https://t1.gstatic.com/licensed-image?q=tbn:ANd9GcTnlF4D6frSxrVjHMMbcQulAVU_hF2RZ3D45iEIKiz3OY4ebeyq2zWYixJ-JwJXKZWt",
            "orbitalPeriod": "Orbital Period: 87.97 days",
            "averageOrbitalSpeed": "Average Orbital Speed: 47.87 km/s",
            "surfaceArea": "Surface Area: 7.48 x 10^7 km²",
            "meanRadius": "Mean Radius: 2,439.7 km",
            "mass": "Mass: 3.3011 x 10^23 kg",
            "moons": "Moons: 0",
            "distanceFromSun": "Distance from Sun: 57.9 million km",
            "atmosphere": "Atmosphere: Thin, composed mainly of oxygen, sodium, hydrogen, helium",
            "temperatureRange": "Temperature Range: -173°C to 427°C",
            "discoveryDate": "Discovery Date: Known to ancient civilizations",
            "rotationPeriod": "Rotation Period: 58.6 days",
            "composition": "Composition: Mostly composed of silicate rock and metals",
            "gravity": "Gravity: 3.7 m/s²",
            "rings": "Rings: None",
            "surfaceFeatures": "Surface Features: Heavily cratered, with some smooth plains",
            "escapeVelocity": "Escape Velocity: 4.25 km/s",
            "density": "Density: 5.427 g/cm³",
            "orbitalInclination": "Orbital Inclination: 7.0°",
            "axialTilt": "Axial Tilt: 0.034°",
            "eccentricity": "Eccentricity: 0.2056"
        },
        {
            "name": "Venus",
            "image":"https://t0.gstatic.com/licensed-image?q=tbn:ANd9GcRtqGYOVmn7rlUHM47dO2MUGjjqp-NkClqUJ7QIxAwGAulcM5kvScQrZSkfglqd92ua",
            "orbitalPeriod": "Orbital Period: 224.7 days",
            "averageOrbitalSpeed": "Average Orbital Speed: 35.02 km/s",
            "surfaceArea": "Surface Area: 4.60 x 10^8 km²",
            "meanRadius": "Mean Radius: 6,051.8 km",
            "mass": "Mass: 4.8675 x 10^24 kg",
            "moons": "Moons: 0",
            "distanceFromSun": "Distance from Sun: 108.2 million km",
            "atmosphere": "Atmosphere: Thick, composed mainly of carbon dioxide with clouds of sulfuric acid",
            "temperatureRange": "Temperature Range: 462°C (hot enough to melt lead)",
            "discoveryDate": "Discovery Date: Known to ancient civilizations",
            "rotationPeriod": "Rotation Period: 243 days (retrograde)",
            "composition": "Composition: Mostly composed of carbon dioxide with traces of nitrogen and other gases",
            "gravity": "Gravity: 8.87 m/s²",
            "rings": "Rings: None",
            "surfaceFeatures": "Surface Features: Volcanoes, vast plains, and highland regions",
            "escapeVelocity": "Escape Velocity: 10.36 km/s",
            "density": "Density: 5.243 g/cm³",
            "orbitalInclination": "Orbital Inclination: 3.4°",
            "axialTilt": "Axial Tilt: 177.4°",
            "eccentricity": "Eccentricity: 0.0067"
        },
        {
            "name": "Earth",
            "image":"https://t1.gstatic.com/licensed-image?q=tbn:ANd9GcQDdxULw7_lHW6S5hHIL4vLEyB5zHHc2MKlHr1NL-6xRFjlEirD_KiIeNjeyhjnt4RH",

            "orbitalPeriod": "Orbital Period: 365.25 days",
            "averageOrbitalSpeed": "Average Orbital Speed: 29.78 km/s",
            "surfaceArea": "Surface Area: 5.10 x 10^8 km²",
            "meanRadius": "Mean Radius: 6,371 km",
            "mass": "Mass: 5.972 x 10^24 kg",
            "moons": "Moons: 1 (The Moon)",
            "distanceFromSun": "Distance from Sun: 149.6 million km",
            "atmosphere": "Atmosphere: Nitrogen (78%), Oxygen (21%), Argon (0.93%), Carbon Dioxide (0.04%)",
            "temperatureRange": "Temperature Range: -88°C to 58°C",
            "discoveryDate": "Discovery Date: Known since prehistoric times",
            "rotationPeriod": "Rotation Period: 24 hours",
            "composition": "Composition: Mostly composed of iron, oxygen, silicon, magnesium, sulfur, nickel, calcium",
            "gravity": "Gravity: 9.81 m/s²",
            "rings": "Rings: None",
            "surfaceFeatures": "Surface Features: Oceans, continents, mountains, and plains",
            "escapeVelocity": "Escape Velocity: 11.19 km/s",
            "density": "Density: 5.514 g/cm³",
            "orbitalInclination": "Orbital Inclination: 0°",
            "axialTilt": "Axial Tilt: 23.44°",
            "eccentricity": "Eccentricity: 0.0167"
        },

        {
            "name": "Mars",
            "image":"https://upload.wikimedia.org/wikipedia/commons/0/0c/Mars_-_August_30_2021_-_Flickr_-_Kevin_M._Gill.png",

            "orbitalPeriod": "Orbital Period: 687 days",
            "averageOrbitalSpeed": "Average Orbital Speed: 24.07 km/s",
            "surfaceArea": "Surface Area: 1.45 x 10^8 km²",
            "meanRadius": "Mean Radius: 3,389.5 km",
            "mass": "Mass: 6.4171 x 10^23 kg",
            "moons": "Moons: 2 (Phobos, Deimos)",
            "distanceFromSun": "Distance from Sun: 227.9 million km",
            "atmosphere": "Atmosphere: Thin, mainly carbon dioxide with traces of nitrogen and argon",
            "temperatureRange": "Temperature Range: -87°C to -5°C",
            "discoveryDate": "Discovery Date: Known since ancient times",
            "rotationPeriod": "Rotation Period: 24.6 hours",
            "composition": "Composition: Mostly composed of iron, magnesium, aluminum, calcium, and potassium",
            "gravity": "Gravity: 3.71 m/s²",
            "rings": "Rings: None",
            "surfaceFeatures": "Surface Features: Volcanoes, valleys, deserts, and polar ice caps",
            "escapeVelocity": "Escape Velocity: 5.03 km/s",
            "density": "Density: 3.9335 g/cm³",
            "orbitalInclination": "Orbital Inclination: 1.85°",
            "axialTilt": "Axial Tilt: 25.19°",
            "eccentricity": "Eccentricity: 0.0934"
        },
        { 
            "name": "Jupiter",
            "image":"https://t2.gstatic.com/licensed-image?q=tbn:ANd9GcREO4TYqbX_pU6DUgg_zfHHBQ4LHVWXJ84Ht2atWX6BGb-VvXbk0WK6rfDmYChBVkBH",

            "orbitalPeriod": "Orbital Period: 4,332.59 days",
            "averageOrbitalSpeed": "Average Orbital Speed: 13.07 km/s",
            "surfaceArea": "Surface Area: 6.1419 x 10^10 km²",
            "meanRadius": "Mean Radius: 69,911 km",
            "mass": "Mass: 1.8982 x 10^27 kg",
            "moons": "Moons: 79 (Io, Europa, Ganymede, Callisto, etc.)",
            "distanceFromSun": "Distance from Sun: 778.5 million km",
            "atmosphere": "Atmosphere: Mostly hydrogen (75%), helium (24%), with traces of methane, water, and ammonia",
            "temperatureRange": "Temperature Range: -145°C to -108°C",
            "discoveryDate": "Discovery Date: Known since ancient times",
            "rotationPeriod": "Rotation Period: 9.9 hours",
            "composition": "Composition: Mostly hydrogen and helium, with a rocky core",
            "gravity": "Gravity: 24.79 m/s²",
            "rings": "Rings: Yes (The rings of Jupiter)",
            "surfaceFeatures": "Surface Features: Gas giant with swirling clouds and the Great Red Spot",
            "escapeVelocity": "Escape Velocity: 59.5 km/s",
            "density": "Density: 1.326 g/cm³",
            "orbitalInclination": "Orbital Inclination: 1.31°",
            "axialTilt": "Axial Tilt: 3.13°",
            "eccentricity": "Eccentricity: 0.0489"
        },
        {
            "name": "Saturn",
            "image":"https://t3.gstatic.com/licensed-image?q=tbn:ANd9GcQUNGwc8h9VqUTHCmp-42Ph6G4YbjA6N2sCxtCTjNgkCFuw0Ms5eZMzZDZI9y97Rh2I",

            "orbitalPeriod": "Orbital Period: 10,759.22 days",
            "averageOrbitalSpeed": "Average Orbital Speed: 9.69 km/s",
            "surfaceArea": "Surface Area: 4.27 x 10^10 km²",
            "meanRadius": "Mean Radius: 58,232 km",
            "mass": "Mass: 5.6834 x 10^26 kg",
            "moons": "Moons: 82 (Titan, Enceladus, Mimas, etc.)",
            "distanceFromSun": "Distance from Sun: 1.4 billion km",
            "atmosphere": "Atmosphere: Mostly hydrogen (96%), helium (3%), with traces of methane and ammonia",
            "temperatureRange": "Temperature Range: -178°C to -139°C",
            "discoveryDate": "Discovery Date: Known since ancient times",
            "rotationPeriod": "Rotation Period: 10.7 hours",
            "composition": "Composition: Mostly hydrogen and helium, with a rocky core",
            "gravity": "Gravity: 10.44 m/s²",
            "rings": "Rings: Yes (The rings of Saturn)",
            "surfaceFeatures": "Surface Features: Gas giant with prominent ring system and hexagonal polar storm",
            "escapeVelocity": "Escape Velocity: 35.5 km/s",
            "density": "Density: 0.687 g/cm³",
            "orbitalInclination": "Orbital Inclination: 2.48°",
            "axialTilt": "Axial Tilt: 26.73°",
            "eccentricity": "Eccentricity: 0.0565"
        },
        {
            "name": "Uranus",
            "image":"https://t2.gstatic.com/licensed-image?q=tbn:ANd9GcSpSO4cQdDF2U3RHXDkKIfis9ofVxh_tC6PF6ZtuX-moYtAOUjruNXgJcfX9auDG9Vk",

            "orbitalPeriod": "Orbital Period: 30,688.5 days",
            "averageOrbitalSpeed": "Average Orbital Speed: 6.81 km/s",
            "surfaceArea": "Surface Area: 8.1156 x 10^9 km²",
            "meanRadius": "Mean Radius: 25,362 km",
            "mass": "Mass: 8.6810 x 10^25 kg",
            "moons": "Moons: 27 (Titania, Oberon, Umbriel, Ariel, etc.)",
            "distanceFromSun": "Distance from Sun: 2.87 billion km",
            "atmosphere": "Atmosphere: Mostly hydrogen (83%), helium (15%), with traces of methane",
            "temperatureRange": "Temperature Range: -224°C to -197°C",
            "discoveryDate": "Discovery Date: Discovered in 1781 by William Herschel",
            "rotationPeriod": "Rotation Period: 17.2 hours",
            "composition": "Composition: Mostly hydrogen and helium, with traces of water, ammonia, and methane ice",
            "gravity": "Gravity: 8.69 m/s²",
            "rings": "Rings: Yes (A faint set of rings)",
            "surfaceFeatures": "Surface Features: Ice giant with a tilted axis of rotation",
            "escapeVelocity": "Escape Velocity: 21.3 km/s",
            "density": "Density: 1.27 g/cm³",
            "orbitalInclination": "Orbital Inclination: 0.77°",
            "axialTilt": "Axial Tilt: 97.77°",
            "eccentricity": "Eccentricity: 0.0457"
        },
        {
            "name": "Neptune",
            "image":"https://t2.gstatic.com/licensed-image?q=tbn:ANd9GcT9RN79wn9Nw-Bt_dn2TjGwLmVo7kxccffCzGa6e1onKI_QyOinDXZ-MMqL_McsRcR1",

            "orbitalPeriod": "Orbital Period: 60,190 days",
            "averageOrbitalSpeed": "Average Orbital Speed: 5.43 km/s",
            "surfaceArea": "Surface Area: 7.6183 x 10^9 km²",
            "meanRadius": "Mean Radius: 24,622 km",
            "mass": "Mass: 1.02413 x 10^26 kg",
            "moons": "Moons: 14 (Triton, Nereid, Proteus, etc.)",
            "distanceFromSun": "Distance from Sun: 4.5 billion km",
            "atmosphere": "Atmosphere: Mostly hydrogen (80%), helium (19%), with traces of methane",
            "temperatureRange": "Temperature Range: -218°C to -200°C",
            "discoveryDate": "Discovery Date: Discovered in 1846 by Johann Galle",
            "rotationPeriod": "Rotation Period: 16.1 hours",
            "composition": "Composition: Mostly hydrogen and helium, with traces of methane and water ice",
            "gravity": "Gravity: 11.15 m/s²",
            "rings": "Rings: Yes (A faint set of rings)",
            "surfaceFeatures": "Surface Features: Ice giant with strong winds and a dark spot similar to Jupiter's Great Red Spot",
            "escapeVelocity": "Escape Velocity: 23.5 km/s",
            "density": "Density: 1.638 g/cm³",
            "orbitalInclination": "Orbital Inclination: 1.77°",
            "axialTilt": "Axial Tilt: 28.32°",
            "eccentricity": "Eccentricity: 0.0113"
        },
        {
            "name": "Sun",
            "image":"https://t0.gstatic.com/licensed-image?q=tbn:ANd9GcQh-AxJRcDz5yLgVfFA_uPIl6gww1aeEmAWM7DGaHTucBrN5JmPYkFGlVjrfQuWd_60",

            "meanRadius":"Mean Radius: 696,340 km",
            "orbitalPeriod": "Orbital Period: Not Applicable (Center of the solar system)",
            "averageOrbitalSpeed": "Average Orbital Speed: 217 km/s",
            "surfaceArea": "Surface Area: 6.09×10^12 square kilometers",
            "diameter": "Diameter: 1,392,684 km",
            "mass": "Mass: 1.989 × 10^30 kg",
            "moons": "Moons: None",
            "escapeVelocity":"Escape Velocity: 617.7 km/s",
            "gravity": "Gravity: 274 m/s²",
            "atmosphere": "Atmosphere: Composed of hydrogen (73.46%) and helium (24.85%), with trace amounts of other elements",
            "temperatureRange": "Temperature Range: 5,500°C (photosphere) to millions of degrees Celsius (corona)",
            "distanceFromSun": "Average Distance from Center of Milky Way Galaxy: Approximately 27,000 light-years",
            "discovery": "Discovery: Observable to humans since prehistoric times",
            "rotationPeriod": "Rotation Period: Approximately 25.05 Earth days at the equator, but differential rotation causes different rotation periods at different latitudes",
            "dayLength": "Day Length: Approximately 25 Earth days at the equator",
            "surfaceFeatures": "Surface Features: Sunspots, solar flares, solar prominences",
            "atmosphericPressure": "Atmospheric Pressure: Extremely low, near vacuum",
            "exploration": "Exploration: Studied extensively with space telescopes like SOHO, SDO, and Parker Solar Probe",
            "potentialForLife": "Potential for Life: None",
            "notableLandmarks": "Notable Landmarks: Sunspots, solar flares",
            "orbitingSpacecraft": "Orbiting Spacecraft: None"
          }
    ]



]





















let data_Arm = [
    [    { 
            "name": "Մերկուրի",
            "image":"https://t1.gstatic.com/licensed-image?q=tbn:ANd9GcTnlF4D6frSxrVjHMMbcQulAVU_hF2RZ3D45iEIKiz3OY4ebeyq2zWYixJ-JwJXKZWt",
            "orbitalPeriod": "Ուղեծրային պարբերություն: 87.97 days",
            "averageOrbitalSpeed": "Ուղեծրային արագություն: 47.87 կմ/վ",
            "surfaceArea": "Մակերևույթի մակերես: 7.48 x 10^7 կմ²",
            "meanRadius": "Շառավիղ: 2,439.7 կմ",
            "mass": "Զանգված: 3.3011 x 10^23 կգ",
            "moons": "Moons: 0",
            "distanceFromSun": "Հեռավորությաւնը արեգակից: 57.9 միլիոն կմ",
            "atmosphere": "Թթվածին  ( 42․0 % )  , Նատրիում ( 29․0 % ), Ջրածին ( 22․0 % ) , Հելիում ( 6․0 % ), Կալիում ( 0․5 % ) ,  մնացածը ( 0․5 % ) ",
            "temperatureRange": "Temperature Range: -173°C to 427°C",
            "discoveryDate": "Discovery Date: Known to ancient civilizations",
            "rotationPeriod": "Rotation Period: 58.6 days",
            "composition": "Composition: Mostly composed of silicate rock and metals",
            "gravity": "Ձգողություն: 3.7 մ/վ²",
            "rings": "Rings: None",
            "surfaceFeatures": "Surface Features: Heavily cratered, with some smooth plains",
            "escapeVelocity": "2-րդ տիեզերական արագություն: 4.25 կմ/վ",
            "density": "Density: 5.427 g/cm³",
            "orbitalInclination": "Orbital Inclination: 7.0°",
            "axialTilt": "Axial Tilt: 0.034°",
            "eccentricity": "Eccentricity: 0.2056"
        },
        {
            "name": "Վեներա",
            "image":"https://t0.gstatic.com/licensed-image?q=tbn:ANd9GcRtqGYOVmn7rlUHM47dO2MUGjjqp-NkClqUJ7QIxAwGAulcM5kvScQrZSkfglqd92ua",
            "orbitalPeriod": "Ուղեծրային պարբերություն: 224.7 days",
            "averageOrbitalSpeed": "Ուղեծրային արագություն: 35.02 կմ/վ",
            "surfaceArea": "Մակերևույթի մակերես: 4.60 x 10^8 կմ²",
            "meanRadius": "Շառավիղ: 6,051.8 կմ",
            "mass": "Զանգված: 4.8675 x 10^24 կգ",
            "moons": "Moons: 0",
            "distanceFromSun": "Հեռավորությաւնը արեգակից: 108.2 միլիոն կմ",
            "atmosphere": "Մթնոլորտ: Ածխաթթու գազ ( 96,5 %) , Ազոտ ( 3,5 % ), Ծծումբի դիօքսիդ (0,015 %) , Արգոն (0,007 %) , Ջուր (0,002 %)  ,Հելիում (0,0012 %)  , Շմոլ գազ (0,0017 %)  , Նեոն (0,0007 %)  ",
            "temperatureRange": "Temperature Range: 462°C (hot enough to melt lead)",
            "discoveryDate": "Discovery Date: Known to ancient civilizations",
            "rotationPeriod": "Rotation Period: 243 days (retrograde)",
            "composition": "Composition: Mostly composed of carbon dioxide with traces of nitrogen and other gases",
            "gravity": "Ձգողություն: 8.87 մ/վ²",
            "rings": "Rings: None",
            "surfaceFeatures": "Surface Features: Volcanoes, vast plains, and highland regions",
            "escapeVelocity": "2-րդ տիեզերական արագություն: 10.36 կմ/վ",
            "density": "Density: 5.243 g/cm³",
            "orbitalInclination": "Orbital Inclination: 3.4°",
            "axialTilt": "Axial Tilt: 177.4°",
            "eccentricity": "Eccentricity: 0.0067"
        },
        {
            "name": "Երկիր",
            "image":"https://t1.gstatic.com/licensed-image?q=tbn:ANd9GcQDdxULw7_lHW6S5hHIL4vLEyB5zHHc2MKlHr1NL-6xRFjlEirD_KiIeNjeyhjnt4RH",

            "orbitalPeriod": "Ուղեծրային պարբերություն: 365.25 days",
            "averageOrbitalSpeed": "Ուղեծրային արագություն: 29.78 կմ/վ",
            "surfaceArea": "Մակերևույթի մակերես: 5.10 x 10^8 կմ²",
            "meanRadius": "Շառավիղ: 6,371 կմ",
            "mass": "Զանգված: 5.972 x 10^24 կգ",
            "moons": "Moons: 1 (The Moon)",
            "distanceFromSun": "Հեռավորությաւնը արեգակից: 149.6 միլիոն կմ",
            "atmosphere": "Մթնոլորտ: Ազոտ (78%), թթվածին (21%), արգոն (0.93%), ածխածնի երկօքսիդ (0.04%)",
            "temperatureRange": "Temperature Range: -88°C to 58°C",
            "discoveryDate": "Discovery Date: Known since prehistoric times",
            "rotationPeriod": "Rotation Period: 24 hours",
            "composition": "Composition: Mostly composed of iron, oxygen, silicon, magnesium, sulfur, nickel, calcium",
            "gravity": "Ձգողություն: 9.81 մ/վ²",
            "rings": "Rings: None",
            "surfaceFeatures": "Surface Features: Oceans, continents, mountains, and plains",
            "escapeVelocity": "2-րդ տիեզերական արագություն: 11.19 կմ/վ",
            "density": "Density: 5.514 g/cm³",
            "orbitalInclination": "Orbital Inclination: 0°",
            "axialTilt": "Axial Tilt: 23.44°",
            "eccentricity": "Eccentricity: 0.0167"
        },

        {
            "name": "Մարս",
            "image":"https://upload.wikimedia.org/wikipedia/commons/0/0c/Mars_-_August_30_2021_-_Flickr_-_Kevin_M._Gill.png",

            "orbitalPeriod": "Ուղեծրային պարբերություն: 687 days",
            "averageOrbitalSpeed": "Ուղեծրային արագություն: 24.07 կմ/վ",
            "surfaceArea": "Մակերևույթի մակերես: 1.45 x 10^8 կմ²",
            "meanRadius": "Շառավիղ: 3,389.5 կմ",
            "mass": "Զանգված: 6.4171 x 10^23 կգ",
            "moons": "Moons: 2 (Phobos, Deimos)",
            "distanceFromSun": "Հեռավորությաւնը արեգակից: 227.9 միլիոն կմ",
            "atmosphere": "Մթնոլորտ: Ածխաթթու գազ (95,32 %) ,Ազոտ (2,7 % ) , Արգոն (1,6 % ) , Թթվածին (0,13 %) , Շմոլ գազ (0,08 %) ,Ջուր (0,021 %) , Ազոտի օքսիդ (0,01 %) ",
            "temperatureRange": "Temperature Range: -87°C to -5°C",
            "discoveryDate": "Discovery Date: Known since ancient times",
            "rotationPeriod": "Rotation Period: 24.6 hours",
            "composition": "Composition: Mostly composed of iron, magnesium, aluminum, calcium, and potassium",
            "gravity": "Ձգողություն: 3.71 մ/վ²",
            "rings": "Rings: None",
            "surfaceFeatures": "Surface Features: Volcanoes, valleys, deserts, and polar ice caps",
            "escapeVelocity": "2-րդ տիեզերական արագություն: 5.03 կմ/վ",
            "density": "Density: 3.9335 g/cm³",
            "orbitalInclination": "Orbital Inclination: 1.85°",
            "axialTilt": "Axial Tilt: 25.19°",
            "eccentricity": "Eccentricity: 0.0934"
        },
        { 
            "name": "Յուպիտեր",
            "image":"https://t2.gstatic.com/licensed-image?q=tbn:ANd9GcREO4TYqbX_pU6DUgg_zfHHBQ4LHVWXJ84Ht2atWX6BGb-VvXbk0WK6rfDmYChBVkBH",

            "orbitalPeriod": "Ուղեծրային պարբերություն: 4,332.59 days",
            "averageOrbitalSpeed": "Ուղեծրային արագություն: 13.07 կմ/վ",
            "surfaceArea": "Մակերևույթի մակերես: 6.1419 x 10^10 կմ²",
            "meanRadius": "Շառավիղ: 69,911 կմ",
            "mass": "Զանգված: 1.8982 x 10^27 կգ",
            "moons": "Moons: 79 (Io, Europa, Ganymede, Callisto, etc.)",
            "distanceFromSun": "Հեռավորությաւնը արեգակից: 778.5 միլիոն կմ",
            "atmosphere": "Մթնոլորտ: Հիմնականում ջրածին (75%), հելիում (24%), մանցածը (1%)",
            "temperatureRange": "Temperature Range: -145°C to -108°C",
            "discoveryDate": "Discovery Date: Known since ancient times",
            "rotationPeriod": "Rotation Period: 9.9 hours",
            "composition": "Composition: Mostly hydrogen and helium, with a rocky core",
            "gravity": "Ձգողություն: 24.79 մ/վ²",
            "rings": "Rings: Yes (The rings of Jupiter)",
            "surfaceFeatures": "Surface Features: Gas giant with swirling clouds and the Great Red Spot",
            "escapeVelocity": "2-րդ տիեզերական արագություն: 59.5 կմ/վ",
            "density": "Density: 1.326 g/cm³",
            "orbitalInclination": "Orbital Inclination: 1.31°",
            "axialTilt": "Axial Tilt: 3.13°",
            "eccentricity": "Eccentricity: 0.0489"
        },
        { 
            "name": "Սատուրն",
            "image":"https://t3.gstatic.com/licensed-image?q=tbn:ANd9GcQUNGwc8h9VqUTHCmp-42Ph6G4YbjA6N2sCxtCTjNgkCFuw0Ms5eZMzZDZI9y97Rh2I",
            "orbitalPeriod": "Ուղեծրային պարբերություն: 10,759.22 days",
            "averageOrbitalSpeed": "Ուղեծրային արագություն: 9.69 կմ/վ",
            "surfaceArea": "Մակերևույթի մակերես: 4.27 x 10^10 կմ²",
            "meanRadius": "Շառավիղ: 58,232 կմ",
            "mass": "Զանգված: 5.6834 x 10^26 կգ",
            "moons": "Moons: 82 (Titan, Enceladus, Mimas, etc.)",
            "distanceFromSun": "Հեռավորությաւնը արեգակից: 1.4 բիլիոն կմ",
            "atmosphere": "Մթնոլորտ: Հիմնականում ջրածին (96%), Հելիում (3%), Մնացածը (1%)",
            "temperatureRange": "Temperature Range: -178°C to -139°C",
            "discoveryDate": "Discovery Date: Known since ancient times",
            "rotationPeriod": "Rotation Period: 10.7 hours",
            "composition": "Composition: Mostly hydrogen and helium, with a rocky core",
            "gravity": "Ձգողություն: 10.44 մ/վ²",
            "rings": "Rings: Yes (The rings of Saturn)",
            "surfaceFeatures": "Surface Features: Gas giant with prominent ring system and hexagonal polar storm",
            "escapeVelocity": "2-րդ տիեզերական արագություն: 35.5 կմ/վ",
            "density": "Density: 0.687 g/cm³",
            "orbitalInclination": "Orbital Inclination: 2.48°",
            "axialTilt": "Axial Tilt: 26.73°",
            "eccentricity": "Eccentricity: 0.0565"
        },
        {
            "name": "Ուրան",
            "image":"https://t2.gstatic.com/licensed-image?q=tbn:ANd9GcSpSO4cQdDF2U3RHXDkKIfis9ofVxh_tC6PF6ZtuX-moYtAOUjruNXgJcfX9auDG9Vk",

            "orbitalPeriod": "Ուղեծրային պարբերություն: 30,688.5 days",
            "averageOrbitalSpeed": "Ուղեծրային արագություն: 6.81 կմ/վ",
            "surfaceArea": "Մակերևույթի մակերես: 8.1156 x 10^9 կմ²",
            "meanRadius": "Շառավիղ: 25,362 կմ",
            "mass": "Զանգված: 8.6810 x 10^25 կգ",
            "moons": "Moons: 27 (Titania, Oberon, Umbriel, Ariel, etc.)",
            "distanceFromSun": "Հեռավորությաւնը արեգակից: 2.87 բիլիոն կմ",
            "atmosphere": "Մթնոլորտ: Հիմնականում ջրածին (83%), Հելիում (15%) , Մնացածը (2%) ",
            "temperatureRange": "Temperature Range: -224°C to -197°C",
            "discoveryDate": "Discovery Date: Discovered in 1781 by William Herschel",
            "rotationPeriod": "Rotation Period: 17.2 hours",
            "composition": "Composition: Mostly hydrogen and helium, with traces of water, ammonia, and methane ice",
            "gravity": "Ձգողություն: 8.69 մ/վ²",
            "rings": "Rings: Yes (A faint set of rings)",
            "surfaceFeatures": "Surface Features: Ice giant with a tilted axis of rotation",
            "escapeVelocity": "2-րդ տիեզերական արագություն: 21.3 կմ/վ",
            "density": "Density: 1.27 g/cm³",
            "orbitalInclination": "Orbital Inclination: 0.77°",
            "axialTilt": "Axial Tilt: 97.77°",
            "eccentricity": "Eccentricity: 0.0457"
        },
        {
            "name": "Նեպտուն",
            "image":"https://t2.gstatic.com/licensed-image?q=tbn:ANd9GcT9RN79wn9Nw-Bt_dn2TjGwLmVo7kxccffCzGa6e1onKI_QyOinDXZ-MMqL_McsRcR1",

            "orbitalPeriod": "Ուղեծրային պարբերություն: 60,190 days",
            "averageOrbitalSpeed": "Ուղեծրային արագություն: 5.43 կմ/վ",
            "surfaceArea": "Մակերևույթի մակերես: 7.6183 x 10^9 կմ²",
            "meanRadius": "Շառավիղ: 24,622 կմ",
            "mass": "Զանգված: 1.02413 x 10^26 կգ",
            "moons": "Moons: 14 (Triton, Nereid, Proteus, etc.)",
            "distanceFromSun": "Հեռավորությաւնը արեգակից: 4.5 բիլիոն կմ",
            "atmosphere": "Մթնոլորտ: Հիմնականում ջրածին (80%), հելիում (19%) , Մնացածը (1%) ",
            "temperatureRange": "Temperature Range: -218°C to -200°C",
            "discoveryDate": "Discovery Date: Discovered in 1846 by Johann Galle",
            "rotationPeriod": "Rotation Period: 16.1 hours",
            "composition": "Composition: Mostly hydrogen and helium, with traces of methane and water ice",
            "gravity": "Ձգողություն: 11.15 մ/վ²",
            "rings": "Rings: Yes (A faint set of rings)",
            "surfaceFeatures": "Surface Features: Ice giant with strong winds and a dark spot similar to Jupiter's Great Red Spot",
            "escapeVelocity": "2-րդ տիեզերական արագություն: 23.5 կմ/վ",
            "density": "Density: 1.638 g/cm³",
            "orbitalInclination": "Orbital Inclination: 1.77°",
            "axialTilt": "Axial Tilt: 28.32°",
            "eccentricity": "Eccentricity: 0.0113"
        },
        {
            "name": "Արև",
            "image":"https://t0.gstatic.com/licensed-image?q=tbn:ANd9GcQh-AxJRcDz5yLgVfFA_uPIl6gww1aeEmAWM7DGaHTucBrN5JmPYkFGlVjrfQuWd_60",
            "meanRadius":" Շառավիղ : 696,340 կմ",
            "orbitalPeriod": "Ուղեծրային պարբերություն: Not Applicable (Center of the solar system)",
            "averageOrbitalSpeed": "Ուղեծրային արագություն: Not Applicable",
            "surfaceArea": "Մակերևույթի մակերես: 6.09×10^12 square kilometers",
            "diameter": "Diameter: 1,392,684 կմ",
            "mass": "Զանգված: 1.989 × 10^30 կգ",
            "moons": "Moons: None",  
            "escapeVelocity":"2-րդ տիեզերական արագություն: 617.7 կմ/վ",
            "gravity": "Ձգողություն: 274 մ/վ²",
            "averageOrbitalSpeed": "Ուղեծրային արագություն: 217 կմ/վ",
            "atmosphere": "Մթնոլորտ: Կազմված է ջրածնից (73,46%) և հելիումից (24,85%) , Մնացածը (1.69 %)",
            "temperatureRange": "Temperature Range: 5,500°C (photosphere) to millions of degrees Celsius (corona)",
            "distanceFromSun": "Միջին հեռավորությունը Ծիր Կաթին Գալակտիկայի կենտրոնից՝ մոտավորապես 27000 լուսային տարի",
            "discovery": "Discovery: Observable to humans since prehistoric times",
            "rotationPeriod": "Rotation Period: Approximately 25.05 Earth days at the equator, but differential rotation causes different rotation periods at different latitudes",
            "dayLength": "Day Length: Approximately 25 Earth days at the equator",
            "surfaceFeatures": "Surface Features: Sunspots, solar flares, solar prominences",
            "atmosphericPressure": "Atmospheric Pressure: Extremely low, near vacuum",
            "exploration": "Exploration: Studied extensively with space telescopes like SOHO, SDO, and Parker Solar Probe",
            "potentialForLife": "Potential for Life: None",
            "notableLandmarks": "Notable Landmarks: Sunspots, solar flares",
            "orbitingSpacecraft": "Orbiting Spacecraft: None"
          }
    ]
]  








// {
//     "name": "Moon",
//     "image":"https://t0.gstatic.com/licensed-image?q=tbn:ANd9GcRtqGYOVmn7rlUHM47dO2MUGjjqp-NkClqUJ7QIxAwGAulcM5kvScQrZSkfglqd92ua",

//     "orbitalPeriod": "Orbital Period: 27.32 Earth days",
//     "averageOrbitalSpeed": "Average Orbital Speed: 1.022 km/s",
//     "surfaceArea": "Surface Area: 3.793 × 10^7 square kilometers",
//     "diameter": "Diameter: 3,474.8 km",
//     "mass": "Mass: 7.342 × 10^22 kg",
//     "moons": "Moons: None",
//     "gravity": "Gravity: 1.62 m/s²",
//     "atmosphere": "Atmosphere: None",
//     "temperatureRange": "Temperature Range: -173°C to 127°C",
//     "distanceFromPlanet": "Average Distance from Earth: 384,400 km",
//     "discovery": "Discovery: Known since ancient times",
//     "rotationPeriod": "Rotation Period: Synchronous rotation with Earth (same as its orbital period)",
//     "dayLength": "Day Length: 27.32 Earth days",
//     "surfaceFeatures": "Surface Features: Maria, Highlands, Craters",
//     "exploration": "Exploration: Various missions including Apollo, Luna, Chang'e, and upcoming Artemis missions",
//     "potentialForLife": "Potential for Life: None",
//     "notableLandmarks": "Notable Landmarks: Tycho Crater, Mare Tranquillitatis (site of Apollo 11 landing)",
//     "orbitingSpacecraft": "Orbiting Spacecraft: Lunar Reconnaissance Orbiter, Chandrayaan, Lunar Atmosphere and Dust Environment Explorer (LADEE)"
// },